Feature: modals for content and share
Vizzuality/nutritions_dashboard pull request #24
Opened 2017-01-04 12:01 UTC by edbrett

Add two modals using modals helper view:
- set modal for interventions on cost packages view
- set basic modal for share modal (designs pending)
- Create helper for data action targets to trigger modal events

2017-01-04 12:21 UTC, geriux commented on app/assets/javascripts/helpers/action_click.js
> +(function(App) {
I don't think a helper for click actions would be useful for what we'll be using it for, what do you think if we just add a listener in the Share Modal, to bind a global click event to a specific class in this case for the footer link?

2017-01-04 12:22 UTC, geriux commented on app/assets/javascripts/templates/modal_share.hbs
> +              <a href="https://www.linkedin.com/shareArticle?mini=true&url={{this.urlEncoded}}&title=Grow%20Asia%20Counter&summary=The Grow Asia Counter allows users to estimate their greenhouse gas
We gotta update this param values :)

2017-01-04 12:22 UTC, geriux commented on app/assets/javascripts/views/share_modal.js
> +      try {
Niceeee!!

2017-01-04 12:24 UTC, geriux commented on app/views/dashboards/show.html.erb
> +      <button class="text -button js-btn-action" data-action="Info:toggle">
Here, like I mentioned above, if we remove the click action helper, we'll avoid to have global events names in the HTML. So adding a global class like js-modal-action or whatever and then binding that in the helper would work too. What  do you think?

2017-01-04 12:24 UTC, geriux requested changes
I've added some comments, let me know what you think!

2017-01-04 12:27 UTC, geriux commented
And for specific modals like the interventions one, I'd just bind the event in the view to open the modal.

2017-01-04 16:58 UTC, merged

2026-09-02 14:27 UTC, mcorriga-lenovo commented on app/assets/javascripts/views/share_modal.js
> +      try {
**Verdict:** fixed.

**Commit:** 1e494e7098 (`fix(qira-core): omit the cloud Qira bearer on loopback MCP`), kept under the file-size ratchet in adaec98e37.

`connect_inner` now passes `direct_url::qira_bearer_for_url`, which yields an empty token for loopback destinations. `McpClient::try_rpc_send` omits `Authorization` when that token is empty; `X-Api-Token` is still sent.

**Test:** `loopback_direct_url_omits_cloud_qira_bearer` fails without the strip (stub records `Authorization` / `X-Api-Token`; asserts no `cloud-qira-secret`, still has `launch-token`).